format = """\
($directory)\
$os\
$git_branch\
$fill\
$nodejs\
$rust\
$golang\
$php\
$bun\
$java\
$c\
$conda\
$zig\
$cmd_duration\
$time\
\n$character\
"""

# Disable the blank line at the beginning of the prompt
add_newline = true

# Command timeout
command_timeout = 3600000

# color and style settings
palette = "catppuccin_mocha"

[fill]
symbol = ' '

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

# Pink mustache icon for the prompt
[character]
success_symbol = "[󱗞](fg:lavender)"
error_symbol = "[󱗞](fg:red)"

# User settings
[username]
style_user = 'bold lavender'
style_root = 'bold maroon'
format = '[󱗞 $user](fg:$style) '
disabled = false
show_always = true

# Directory settings
[directory]
format = "[$path](bold $style)[$read_only]($read_only_style) "
truncation_length = 2
style = "fg:mauve"
read_only_style = "fg:mauve"
before_repo_root_style = "fg:mauve"
truncation_symbol = "…/"
truncate_to_repo = true
read_only = "  "

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[cmd_duration]
format = " took [ $duration]($style) "
style = "bold fg:lavender"
min_time = 500

[git_branch]
format = "-> [$symbol$branch]($style) "
style = "bold fg:green"
symbol = " "

[git_status]
format = '[$all_status$ahead_behind ]($style)'
style = "fg:text bg:surface0"

[docker_context]
disabled = true
symbol = " "

[python]
disabled = false
format = '[${symbol}${pyenv_prefix}(${version})( \($virtualenv\))](fg:yellow)($style)'
symbol = " "
version_format = "${raw}"

[java]
format = '[[ $symbol ($version) ](fg:red)]($style)'
version_format = "${raw}"
symbol = " "
disabled = false

[c]
format = '[[ $symbol ($version) ](fg:sky)]($style)'
symbol = " "
version_format = "${raw}"
disabled = false

[zig]
format = '[[ $symbol ($version) ](fg:peach)]($style)'
version_format = "${raw}"
disabled = false

[bun]
version_format = "${raw}"
format = '[[ $symbol ($version) ](fg:subtext0)]($style)'
disabled = false

[nodejs]
symbol = ""
format = '[[ $symbol ($version) ](fg:green)]($style)'

[rust]
symbol = ""
format = '[[ $symbol ($version) ](fg:red)]($style)'

[golang]
symbol = ""
format = '[[ $symbol ($version) ](fg:sky)]($style)'

[php]
symbol = ""
format = '[[ $symbol ($version) ](fg:yellow)]($style)'

[time]
disabled = false
time_format = "%R"
format = '[[  $time ](fg:overlay2)]($style)'
