[colors.bright]
black = "#282a40"
blue = "#6378ff"
cyan = "#8ffff2"
green = "#0091ff"
magenta = "#7a7dff"
red = "#336dff"
white = "#bce6e0"
yellow = "#47ffd4"

[colors.normal]
black = "#181a29"
blue = "#6378ff"
cyan = "#8ffff2"
green = "#0091ff"
magenta = "#7a7dff"
red = "#336dff"
white = "#bdfff7"
yellow = "#47ffd4"

[colors.primary]
background = "#011627"
foreground = "#4fb3ff"
