[colors.bright]
black = "#282a40"
blue = "#4dbd72"
cyan = "#4ddb7c"
green = "#00bb00"
magenta = "#2e9e3e"
red = "#007700"
white = "#57d979"
yellow = "#7fde5d"

[colors.normal]
black = "#181a29"
blue = "#4dbd72"
cyan = "#4ddb7c"
green = "#00bb00"
magenta = "#2e9e3e"
red = "#007700"
white = "#67e689"
yellow = "#7fde5d"

[colors.primary]
background = "#0f101a"
foreground = "#67e689"
