[colors.bright]
black = "#727169"   # Bright ANSI Black
blue = "#7fb4ca"    # Bright ANSI Blue
cyan = "#7aa89f"    # Bright ANSI Cyan
green = "#98bb6c"   # Bright ANSI Green
magenta = "#938aa9" # Bright ANSI Magenta
red = "#e82424"     # Bright ANSI Red
white = "#dcd7ba"   # Bright ANSI White
yellow = "#e6c384"  # Bright ANSI Yellow

[colors.cursor]
cursor = "#c8c093" # Cursor color
text = "#181616"   # Cursor text color

[colors.normal]
black = "#090618"   # ANSI Black
blue = "#7e9cd8"    # ANSI Blue
cyan = "#6a9589"    # ANSI Cyan
green = "#76946a"   # ANSI Green
magenta = "#957fb8" # ANSI Magenta
red = "#c34043"     # ANSI Red
white = "#c8c093"   # ANSI White
yellow = "#c0a36e"  # ANSI Yellow

[colors.primary]
background = "#181616" # Background color
foreground = "#dcd7ba"

[colors.selection]
background = "#2d4f67" # Selection background color
text = "#c8c093"       # Selection text color
